name: Build
on: [ push, pull_request ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: namespace-profile-linux-default
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle
      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this
      - name: "jdk"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: "" # namespace handles this
      - name: "build"
        run: ./gradlew build --init-script=/tmp/init.gradle
      - name: "publish snapshot"
        if: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
        run: ./gradlew publish --init-script=/tmp/init.gradle
        env:
          ORG_GRADLE_PROJECT_paperUsername: "${{ secrets.ARTIFACTORY_USERNAME }}"
          ORG_GRADLE_PROJECT_paperPassword: "${{ secrets.ARTIFACTORY_PASSWORD }}"
